### ISSUE TITLE
Activation Link not being sent .. How to congfigure that ?

### ISSUE THREAD

**Issue by binualexander** [ebelter/userauth#1]
Please include instructions on actually making the rails app send activation links ...

**Comment by ebelter** [comment]
When running in dev mode, the config is set to not send emails:

# Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

In production, you would need to set the config up to use whatever mail server you want to use:

https://www.railstutorial.org/book/account_activation_password_reset#sec-email_in_production

To activate the user in dev, the activation link is printed to the logs (log/development.log). Use that link to activate the user.

**Comment by binualexander** [comment]
Thanks ....

**Comment by ebelter** [comment]
NP! Good luck!
